#:schema node_modules/wrangler/config-schema.json
name = "jorgechato-com"
compatibility_date = "2024-10-22"
pages_build_output_dir = "./build/client"

[vars]
NOMADLIST_USERNAME = "jorgechato"
GITHUB_OWNER = "jorgechato"
GITHUB_GIST = "7ac38bc8be549240ff1835f83cc74adf"
