/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/models/Island.glb -t
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    group1651290667: THREE.Mesh;
    group615116044: THREE.Mesh;
    group694142508: THREE.Mesh;
    group1810082506: THREE.Mesh;
    group1493570185: THREE.Mesh;
    group1035743550: THREE.Mesh;
    group1061609037: THREE.Mesh;
    group575109798: THREE.Mesh;
    group1441309711: THREE.Mesh;
    group1094615483: THREE.Mesh;
    group125708411: THREE.Mesh;
    group698118262: THREE.Mesh;
  };
  materials: {
    mat20: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Island.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1651290667.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group615116044.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group694142508.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1810082506.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1493570185.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1035743550.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1061609037.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group575109798.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1441309711.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1094615483.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group125708411.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group698118262.geometry} material={materials.mat20} />
    </group>
  );
}

useGLTF.preload('/models/Island.glb');
