/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/models/Soju.glb -t
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    group1240572113: THREE.Mesh;
    group1799578475: THREE.Mesh;
    group513687082: THREE.Mesh;
    group517794709: THREE.Mesh;
    group400981136: THREE.Mesh;
    group1966730439: THREE.Mesh;
    group684520965: THREE.Mesh;
    group2066391043: THREE.Mesh;
    group116389814: THREE.Mesh;
    group834184757: THREE.Mesh;
    group935593738: THREE.Mesh;
    group1385677405: THREE.Mesh;
    group118863927: THREE.Mesh;
    group1161379559: THREE.Mesh;
    group279574652: THREE.Mesh;
    group1082600607: THREE.Mesh;
    group2113453419: THREE.Mesh;
    group737774451: THREE.Mesh;
  };
  materials: {
    mat10: THREE.MeshStandardMaterial;
    mat24: THREE.MeshStandardMaterial;
    mat23: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Soju.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1240572113.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1799578475.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group513687082.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group517794709.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group400981136.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1966730439.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group684520965.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group2066391043.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group116389814.geometry} material={materials.mat24} />
      <mesh geometry={nodes.group834184757.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group935593738.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1385677405.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group118863927.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1161379559.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group279574652.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1082600607.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2113453419.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group737774451.geometry} material={materials.mat23} />
    </group>
  );
}

useGLTF.preload('/models/Soju.glb');
