name: 'Deploy to Cloudflare'
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: "http://127.0.0.1:8080"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@familyallovertheworld'

      - name: Creating .npmrc
        run: |
          echo "@familyallovertheworld:registry=https://npm.pkg.github.com" >> .npmrc
          echo "@faotw:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: "npm run pages:build"

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: brain-familyalloverthe-world
          directory: ".vercel/output/static"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          wranglerVersion: '3'
