name: 'Review Dog'
on:
  pull_request:
permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          reporter: github-pr-review
          fail_on_error: true
          eslint_flags: '**/*.{ts,tsx,js,jsx}'
